### ISSUE TITLE
ExchangeType Error 

### ISSUE THREAD

**Issue by NareeyaChenu** [13angs/simple-rabbitmq#1]
``` bash 
Unhandled exception. RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text='PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'simple_rabbitmq_exchange' in vhost '/': received 'fanout' but current is 'topic'', classId=40, methodId=10
```

**Comment by 13angs** [comment]
> ```shell
> Unhandled exception. RabbitMQ.Client.Exceptions.OperationInterruptedException: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text='PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'simple_rabbitmq_exchange' in vhost '/': received 'fanout' but current is 'topic'', classId=40, methodId=10
> ```

## Solution
The error was fixed in #2 

1. Go to Rabbitmq ui
2. remove your exchange

![image](https://user-images.githubusercontent.com/103742354/202592684-069b2ebe-1654-4d5f-b533-9d9b7fabb08e.png)

3. restore the package

if you get an error similar to `NU1102: Unable to find package` try follow [this](https://stackoverflow.com/questions/54585764/error-nu1102-unable-to-find-package-nuget-frameworks-with-version-4-9-3)
